// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HardWareTech.DATA.Models
{
    public partial class Produto
    {
        public Produto()
        {
            ProdutoClienteManutencao = new HashSet<ProdutoClienteManutencao>();
            ProdutoVenda = new HashSet<ProdutoVenda>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("nome_produto")]
        [StringLength(100)]
        [Unicode(false)]
        public string NomeProduto { get; set; }
        [Column("descricao")]
        [StringLength(500)]
        [Unicode(false)]
        public string Descricao { get; set; }
        [Column("preco", TypeName = "decimal(10, 2)")]
        public decimal Preco { get; set; }
        public int? Estoque { get; set; }
        [Column("datacadastro", TypeName = "date")]
        public DateTime Datacadastro { get; set; }
        [Column("marca")]
        [StringLength(50)]
        [Unicode(false)]
        public string Marca { get; set; }
        [Column("idCategoria")]
        public int IdCategoria { get; set; }

        [ForeignKey("IdCategoria")]
        [InverseProperty("Produto")]
        public virtual Categoria IdCategoriaNavigation { get; set; }
        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<ProdutoClienteManutencao> ProdutoClienteManutencao { get; set; }
        [InverseProperty("IdProdutoNavigation")]
        public virtual ICollection<ProdutoVenda> ProdutoVenda { get; set; }
    }
}