// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HardWareTech.DATA.Models
{
    [Table("Produto_Venda")]
    public partial class ProdutoVenda
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idProduto")]
        public int IdProduto { get; set; }
        [Column("quantidade")]
        public int Quantidade { get; set; }
        [Column("valorUnitario", TypeName = "decimal(10, 2)")]
        public decimal ValorUnitario { get; set; }
        [Column("idVenda")]
        public int IdVenda { get; set; }

        [ForeignKey("IdProduto")]
        [InverseProperty("ProdutoVenda")]
        public virtual Produto IdProdutoNavigation { get; set; }
        [ForeignKey("IdVenda")]
        [InverseProperty("ProdutoVenda")]
        public virtual Venda IdVendaNavigation { get; set; }
    }
}