// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HardWareTech.DATA.Models
{
    public partial class Usuario
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome_usuario")]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeUsuario { get; set; }
        [Required]
        [Column("login")]
        [StringLength(50)]
        [Unicode(false)]
        public string Login { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("senha")]
        [StringLength(50)]
        [Unicode(false)]
        public string Senha { get; set; }
        [Column("datacadastro", TypeName = "date")]
        public DateTime Datacadastro { get; set; }

        public bool SenhaValida(string senha)
        {
            return Senha == senha;
        }
    }
}