// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HardWareTech.DATA.Models
{
    public partial class Venda
    {
        public Venda()
        {
            ProdutoVenda = new HashSet<ProdutoVenda>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idCliente")]
        public int IdCliente { get; set; }
        [Column("dataVenda", TypeName = "datetime")]
        public DateTime DataVenda { get; set; }
        [Column("valorTotal", TypeName = "decimal(10, 2)")]
        public decimal ValorTotal { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("Venda")]
        public virtual Cliente IdClienteNavigation { get; set; }
        [InverseProperty("IdVendaNavigation")]
        public virtual ICollection<ProdutoVenda> ProdutoVenda { get; set; }
    }
}